//
// Created by Robert LUTT on 1/13/18.
//

#ifndef RETRO_MACROS_HPP
#define RETRO_MACROS_HPP

#define ENEMYCOUNT 50
#define PARTICLECOUNT 100
#define BULLETCOUNT ((ENEMYCOUNT + 1) * 100)
#define TOTALOBJ (ENEMYCOUNT + BULLETCOUNT + 1 + PARTICLECOUNT)
#define COLLIDABLE (ENEMYCOUNT + BULLETCOUNT + 1)
#define FPS 60
#define CLOCKS_PER_FRAME (CLOCKS_PER_SEC / FPS)

#endif //RETRO_MACROS_HPP
